spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/server_ducky
    username: postgres
    password: 24102002
#    url: jdbc:postgresql://dpg-cplbb60cmk4c739l5jjg-a.render.com:5432/server_ducky_i5jm
#    username: salmon
#    password: UxanmKbAtberQG8t2i25aoDGPgRP6oCr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
